### ISSUE TITLE
feature request: Consider conditionally compiling on `Send` and `Sync` bounds

### ISSUE THREAD

**Issue by matheus23** [eigerco/blockstore#2]
With wasm_bindgen, the [`JsValue`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsValue.html#impl-Send-for-JsValue) and [`JsFuture`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/struct.JsFuture.html) types are [`!Sync`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsValue.html#impl-Send-for-JsValue).

I've seen that you've been using [`SendWrapper`](https://docs.rs/send_wrapper/latest/send_wrapper/) [in your implementation](https://github.com/eigerco/blockstore/blob/main/src/indexed_db_blockstore.rs#L17) so far, but personally would prefer solutions that don't have the potential to panic at runtime.

Here's examples for using conditional compilation for `Send` and `Sync` bounds:
- [`noosphere-storage`](https://github.com/subconsciousnetwork/noosphere/blob/main/rust/noosphere-storage/src/store.rs#L21-L22) and their [`ConditionalSync` trait](https://github.com/subconsciousnetwork/noosphere/blob/main/rust/noosphere-common/src/sync.rs#L10)
- [`wnfs-common`](https://github.com/wnfs-wg/rs-wnfs/blob/main/wnfs-common/src/blockstore.rs#L58) (notice the `+ CondSend` bound in the return value of the future) and its [`send_sync_poly.rs`](https://github.com/wnfs-wg/rs-wnfs/blob/main/wnfs-common/src/utils/send_sync_poly.rs)

**Comment by oblique** [comment]
Currently almost all the Rust WASM infrastructure relies on `SendWrapper` because multi-threading in browsers is still not well defined and everything is single-threaded. I do like your proposal but we still need to see in practice how it will affect [beetswap](https://github.com/eigerco/beetswap) and [lumina-node](https://github.com/eigerco/lumina/tree/main/node). Feel free to send a PR and we will evaluate it at that time.

**Comment by matheus23** [comment]
> Feel free to send a PR and we will evaluate it at that time.

Will definitely do this, but only if/after #6 is merged, because #6 slightly changes the way Send bounds are applied (`impl Future + Send` vs. `async_trait(?Send)`/`async_trait`).
