### ISSUE TITLE
Clarification on use of `idb` crate.

### ISSUE THREAD

**Issue by devashishdxt** [eigerco/blockstore#28]
Hi @fl0rek. I was looking at the usage of `idb` crate in `blockstore` and noticed that you added direct dependency of `idb` crate just for error conversion [here](https://github.com/eigerco/blockstore/pull/24/files#diff-c567df740adadba0d1541d50715ad37324e47bbf324fb722f342eaaccb432d1bR115). Is the something specific to this project or `rexie` unintentionally exposes an API that returns `idb::Error`?

**Comment by fl0rek** [comment]
@devashishdxt actually I remembered what it was initially. 
[`KeyRange`](https://docs.rs/rexie/latest/rexie/struct.KeyRange.html) error types are idb errors not wrapped in `rexie::Error::IdbError`, so it's a bit of a leak indeed.
